language: c

notifications:
  email: false

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

script:
  - ./autogen.sh
  - ./configure --prefix=/tmp/
  - make
  - make install
